// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.AplicationContext;

#nullable disable

namespace Warehouse.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Model.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "count");

                    b.Property<DateOnly>("DateOrder")
                        .HasColumnType("date")
                        .HasAnnotation("Relational:JsonPropertyName", "dateOrder");

                    b.Property<DateOnly>("DateStatus")
                        .HasColumnType("date")
                        .HasAnnotation("Relational:JsonPropertyName", "dateStatus");

                    b.Property<string>("ManagerOrder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "managerOrder");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "material");

                    b.Property<float>("Size")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "size");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Warehouse.Model.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<DateOnly>("DateStatus")
                        .HasColumnType("date")
                        .HasAnnotation("Relational:JsonPropertyName", "dateStatus");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "material");

                    b.Property<float>("Size")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "size");

                    b.Property<int>("StatusWarehouse")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "vendor");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });
#pragma warning restore 612, 618
        }
    }
}
